// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_vMJShl-PRxieiFuaP87Tc1gBffVUyZk',
    appId: '1:962739787299:web:ed9b397e103afb14824396',
    messagingSenderId: '962739787299',
    projectId: 'tabuapp-4325a',
    authDomain: 'tabuapp-4325a.firebaseapp.com',
    databaseURL: 'https://tabuapp-4325a-default-rtdb.firebaseio.com',
    storageBucket: 'tabuapp-4325a.firebasestorage.app',
    measurementId: 'G-YTR8ZF2NMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8WTqOuCCqMcxc0d0nRNQFr-p8ynrwuUY',
    appId: '1:962739787299:android:07559ed97ecde912824396',
    messagingSenderId: '962739787299',
    projectId: 'tabuapp-4325a',
    databaseURL: 'https://tabuapp-4325a-default-rtdb.firebaseio.com',
    storageBucket: 'tabuapp-4325a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa00Dh6ruuFi3ZGKvTygaui7JxFonFMIg',
    appId: '1:962739787299:ios:c4e4f065fe11a06f824396',
    messagingSenderId: '962739787299',
    projectId: 'tabuapp-4325a',
    databaseURL: 'https://tabuapp-4325a-default-rtdb.firebaseio.com',
    storageBucket: 'tabuapp-4325a.firebasestorage.app',
    iosBundleId: 'com.tabu.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa00Dh6ruuFi3ZGKvTygaui7JxFonFMIg',
    appId: '1:962739787299:ios:c4e4f065fe11a06f824396',
    messagingSenderId: '962739787299',
    projectId: 'tabuapp-4325a',
    databaseURL: 'https://tabuapp-4325a-default-rtdb.firebaseio.com',
    storageBucket: 'tabuapp-4325a.firebasestorage.app',
    iosBundleId: 'com.tabu.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_vMJShl-PRxieiFuaP87Tc1gBffVUyZk',
    appId: '1:962739787299:web:f4eea65a065499b6824396',
    messagingSenderId: '962739787299',
    projectId: 'tabuapp-4325a',
    authDomain: 'tabuapp-4325a.firebaseapp.com',
    databaseURL: 'https://tabuapp-4325a-default-rtdb.firebaseio.com',
    storageBucket: 'tabuapp-4325a.firebasestorage.app',
    measurementId: 'G-KSS71E0LT3',
  );

}